- name: Install standard packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - etckeeper                 # handle /etc in git FIXME - needs config
    - htop                      # comfortable top
    - molly-guard               # protects machines from accidental shutdowns/reboots
    - needrestart               # check which daemons need to be restarted after library upgrades
    - screen                    # console multiplexer
    - netcat-openbsd            # network tool
    - tig                       # git viewer
    - tmux                      # console multiplexer
    - unattended-upgrades       # automatic installation of security upgrades
    - vim-tiny                  # minimal console vim

- name: Remove useless packages
  become: true
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - acpi
    - acpid
    - at
    - debian-faq
    - dmidecode
    - eject
    - ftp
    - iamerican
    - ibritish
    - ispell
    - laptop-detect
    - libclass-isa-perl
    - libswitch-perl
    - m4
    - mutt
    - nano
    - nfs-common
    - os-prober
    - pinentry-gtk2
    - procmail
    - rdnssd
    - rpcbind
    - telnet
    - texinfo
    - vim-tiny
    - wamerican
    - xauth
    - xdg-user-dirs
