- name: Install standard packages
  become: true
  apt: name={{ item }} state=preset
  with_items:
    - etckeeper                 # handle /etc in git FIXME - needs config
    - apt                       # debian packet management
    - htop                      # comfortable top
    - locales-all               # FIXME - needs review, do we need all?
    - mc                        # midnight commander
    - molly-guard               # protects machines from accidental shutdowns/reboots
    - needrestart               # check which daemons need to be restarted after library upgrades
    - pinentry-curses           # console based password entry FIXME - what needs this?
    - rng-tools                 # daemon to use a hardware random number generator
    - screen                    # console multiplexer
    - netcat-openbsd            # network tool
    - tig                       # git viewer
    - tmux                      # console multiplexer
    - debfoster                 # remove unneeded debian packets
    - unattended-upgrades       # automatic installation of security upgrades
    - vim-nox                   # console vim with scripting FIXME - need scripting?

- name: Remove useless packages
  become: true
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - acpi
    - acpid
    - at
    - debian-faq
    - dmidecode
    - eject
    - ftp
    - iamerican
    - ibritish
    - ispell
    - laptop-detect
    - libclass-isa-perl
    - libswitch-perl
    - m4
    - mutt
    - nano
    - nfs-common
    - os-prober
    - pinentry-gtk2
    - procmail
    - rdnssd
    - rpcbind
    - telnet
    - texinfo
    - vim-tiny
    - wamerican
    - xauth
    - xdg-user-dirs
